### ISSUE TITLE
Bug: Does not handle strings of 0s longer than 19.

### ISSUE THREAD

**Issue by avighnac** [avighnac/polymath#2]
- `000000000000000000000000000000000000000000000000000000000000000000`
- `000000000000000000000000000000000000000000000000000000000000000001`
- `1000000000000000000000000000000000000000000000000000000000000000001`

Converting these to a base 10 string causes a segmentation fault, or weird behaviour (for the last one)

```c
#include <polymath.h>
#include <stdio.h>
#include <stdlib.h>

int main() {
  char number[] =
      "1000000000000000000000000000000000000000000000000000000000000000001";

  struct plm_number a = plm_from_base10_string(number);

  char *str = plm_to_base10_string(&a);
  printf("%s\n", str);

  plm_free(&a);
  free(str);

  return 0;
}
```

This is due to the way the numbers are internally represented.

**Comment by AaravMalani** [comment]
Suggestion to mention that it only fails for strings of 0s longer than 19
